title: Arduino Adventure No. 1
tags:
  - Arduino Mega 2560
  - Ramps 1.4
  - LCD
  - hello world
categories:
  - Arduino
short: I recently bought an Arduino Mega 2560 with a Ramps 1.4 shield the corresponding stepper motor drivers and an LCD screen. The ultimate goal is to build my first 3d printer using spare parts and then use that printer to make parts for a better one.
date: 2017-01-14 12:12:21