title: Maven Plugin for Partial Patches
tags:
  - java
  - maven
  - patch
categories:
  - Java
short: Sometimes I need to create a partial patch for some dev environment, so I made this plugin to copy either the classes or the java source code to where I wished.
date: 2016-12-10 20:14:21