title: A comperative study of the Turkey-Israel partnership and the Greek-Cyprus-Israel axis
categories: [geopolitics]
tags: [geopolitics, israel, greece, turkey, cyprus]
date: 2014-05-21 20:15:16
short: The South-East Mediterranean is one of the most volatile regions on the planet. Currently, there are several hotspots in the Middle East and many unresolved issues waiting to break out. This study that compares the relations and most importantly