title: Writing logs to file from a cluster
date: 2017-10-14 13:21:30
categories: [Golang]
short: Recently, at work, I kept falling into a problem regarding log files. The logs are written on the machine the cluster node is in, making their retrieval time consuming.
tags: [go, golang, logging, gRPC, protobuf]
