title: The Underlying Dilemma in the Greek Referendum
date: 2015-07-25 23:52:31
categories: [Geopolitics]
short: This week is largely considered a historic one due to the Greek referendum. On July 5th the Greek public will decide whether to accept the troika proposal or not.
tags: [geopolitics, huntington, mackinder, referendum, greece]